CREATE DATABASE juan_mecanico;
USE juan_mecanico;

CREATE TABLE HISTORIAL_ERRORES (
    ERROR_ID INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(100) NOT NULL
);

CREATE TABLE TIPOS_TEL_CLIENTE (
    ID_TEL_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE CLIENTE (
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY, 
    NOMBRE VARCHAR(100) NOT NULL,           
    APELLIDO VARCHAR(100) NOT NULL,          
    EMAIL VARCHAR(255) UNIQUE NOT NULL,          
    PASSWORD VARCHAR(255) NOT NULL,          
    TELEFONO VARCHAR(15),                  
    FECHA_CREACION DATETIME DEFAULT CURRENT_TIMESTAMP, 
    ULTIMA_SESION DATETIME,
    ROL VARCHAR(20) DEFAULT 'usuario' 
);

CREATE TABLE SERVICIO (
    ID_SERVICIO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL,
    COSTO DECIMAL(12, 2) NOT NULL
);

INSERT INTO `servicio` (`DESCRIPCION`, `COSTO`) VALUES
('Diagnostico General', 20.00),
('Mantenimiento', 30.00),
('Chapisteria y Pintura', 100.00),
('Alineacion', 15.00);


CREATE TABLE CITA (
    ID_CITA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    FECHA_SOLICITUD DATE NOT NULL,
    Descripcion VARCHAR(255),
    HORA TIME DEFAULT NULL,
    ID_SERVICIO INT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO) ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE CLIENTE_TEL (
    ID_CLIENTE INT,
    ID_TEL_CLIENTE INT,
    NUM_TELEFONO VARCHAR(255),
    PRIMARY KEY (ID_CLIENTE, ID_TEL_CLIENTE),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
    FOREIGN KEY (ID_TEL_CLIENTE) REFERENCES TIPOS_TEL_CLIENTE(ID_TEL_CLIENTE)
);

CREATE TABLE AUTOMOVIL (
    ID_AUTOMOVIL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    MATRICULA VARCHAR(50) NOT NULL,
    MARCA VARCHAR(100) NOT NULL,
    COLOR VARCHAR(50),
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);


CREATE TABLE FACTURA (
    ID_FACTURA INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    FECHA_EMISION DATE NOT NULL,
    IMPORTE DECIMAL(12, 2) NOT NULL,
    IMPUESTO DECIMAL(12, 2) NOT NULL,
    TOTAL DECIMAL(12, 2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
);

CREATE TABLE ORDEN_SERVICIO (
    ID_ORDEN INT,
    ID_SERVICIO INT,
    COSTO_PERSONALIZADO DECIMAL(12, 2) NOT NULL,
    PRIMARY KEY (ID_ORDEN, ID_SERVICIO),
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN_TRABAJO(ID_ORDEN),
    FOREIGN KEY (ID_SERVICIO) REFERENCES SERVICIO(ID_SERVICIO)
);

CREATE TABLE TIPOS_EMAIL_MECANICO (
    ID_EMAIL_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE TIPOS_TEL_MECANICO (
    ID_TEL_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    DESCRIPCION VARCHAR(255) NOT NULL
);

CREATE TABLE MECANICO (
    ID_MECANICO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    APELLIDO VARCHAR(100) NOT NULL,
    CIUDAD VARCHAR(100),
    EMAIL VARCHAR(255),
    PROVINCIA VARCHAR(100),
    BARRIADA VARCHAR(100),
    CIP VARCHAR(20) UNIQUE
);

CREATE TABLE MECANICO_TEL (
    ID_MECANICO INT,
    ID_TEL_MECANICO INT,
    NUM_TELEFONO VARCHAR(255),
    PRIMARY KEY (ID_MECANICO, ID_TEL_MECANICO),
    FOREIGN KEY (ID_MECANICO) REFERENCES MECANICO(ID_MECANICO),
    FOREIGN KEY (ID_TEL_MECANICO) REFERENCES TIPOS_TEL_MECANICO(ID_TEL_MECANICO)
);

CREATE TABLE ASIGNACIONES (
    ID_MECANICO INT,
    ID_ORDEN INT,
    FECHA_ASIGNACION DATE NOT NULL,
    PRIMARY KEY (ID_MECANICO, ID_ORDEN),
    FOREIGN KEY (ID_MECANICO) REFERENCES MECANICO(ID_MECANICO),
    FOREIGN KEY (ID_ORDEN) REFERENCES ORDEN_TRABAJO(ID_ORDEN)
);


